services:
  mongodb:
    image: mongo:latest
    container_name: book-manager-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: book-manager
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    depends_on: [mongodb]
    environment:
      PORT: 8081
      DATABASE: book-manager
      JWT_SECRET: book-mangar-library-secret
      DBURI: mongodb://admin:admin123@mongodb:27017/book-manager?authSource=admin
    ports:
      - "8081:8081"

volumes:
  mongo_data:
